AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0

Style/CaseIndentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Lint/RescueException:
  Enabled: false
Metrics/MethodLength:
  Max: 100
Metrics/ClassLength:
  Max: 250
Metrics/AbcSize:
  Max: 60
Metrics/BlockLength:
  Max: 50
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Layout/EmptyLineAfterGuardClause:
  Enabled: false
