language: ruby
rvm:
  - 2.3.3
cache: bundler
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libmagic1
      - libmagic-dev
install:
  - travis_retry bundle update
script:
  - rake

